name: gen_fingerprints

on:
  push:
  schedule:
    # At 12:27AM every Saturday
    - cron: "27 00 * * 6"

concurrency:
  group: gen_fingerprints-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gen_fingerprints:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: scripts/requirements.txt
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Refresh readme + fingerprints.json
        run: python3 scripts/gen_fingerprints.py overwrite_json overwrite_readme
      - name: Setup node.js
        uses: actions/setup-node@v6
      - name: Install prettier
        run: npm install --save-dev --save-exact prettier
      - name: Run prettier
        run: npx prettier --write .
      - name: Commit readme + fingerprints.json
        uses: EndBug/add-and-commit@v9
        with:
          add: '["README.md", "fingerprints.json"]'
          default_author: github_actions
          message: "refresh README + fingerprints.json"
